Repository FRONTENDBOOTCAMP-11th/baroFarm, pull requests merged in 2024-12, with the labels that each got.

#4 Feature3/route helmet/jinsu
  src/App.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/components/layout/readme.md
  src/components/readme.md
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/readme.md
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/CategoryPage.jsx
  src/pages/market/MenuPage.jsx
  src/pages/market/ProductDetailPage.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/market/ProductReviewPage.jsx
  src/pages/market/SearchPage.jsx
  src/pages/market/SearchResultsPage.jsx
  src/pages/market/readme.md
  src/pages/readme.md
  src/pages/user/BookmarkPage.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
  src/pages/user/SignupPage.jsx
  src/pages/user/readme.md
  src/routes.jsx
Labels: P1, feature

#10 fix: footer 너비 조정 (#9)
  src/components/layout/Footer.jsx
  src/components/layout/index.jsx
Labels: bug

#12 feat: 카테고리 메뉴 & 페이지 연결 (#11)
  public/icons/icon_forward_thin.svg
  public/images/menu/Fruit.svg
  public/images/menu/Kimchi.svg
  public/images/menu/Livestock.svg
  public/images/menu/Rice.svg
  public/images/menu/Ricecake.svg
  public/images/menu/Seafood.svg
  public/images/menu/Simple.svg
  public/images/menu/Vegetable.svg
  src/components/MenuItem.jsx
  src/components/layout/index.jsx
  src/pages/market/MenuPage.jsx
Labels: feature

#14 Feature/13 category
  public/images/Sample1.svg
  public/images/Sample2.svg
  src/components/MenuItem.jsx
  src/components/Product.jsx
  src/components/layout/Footer.jsx
  src/pages/market/CategoryPage.jsx
Labels: P1, feature

#16 Feature/6 login page/eunji
  src/pages/user/LoginPage.jsx
  src/routes.jsx
Labels: P1, feature

#17 feature: Header 컴포넌트 생성
  public/icons/icon_x_black.svg
  src/components/HeaderIcon.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
Labels: P1, feature

#30 Feature/21 main page UI/jinsu
  public/images/menu/Fruit_full.svg
  public/images/menu/Kimchi_full.svg
  public/images/menu/Livestock_full.svg
  public/images/menu/Rice_full.svg
  public/images/menu/Ricecake_full.svg
  public/images/menu/Seefood_full.svg
  public/images/menu/Simple_full.svg
  public/images/menu/Vegetable_full.svg
  src/components/ProductBig.jsx
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/index.css
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/SearchBestPage.jsx
  src/pages/market/SearchNewPage.jsx
  src/pages/market/SearchSeasonalPage.jsx
  src/routes.jsx
Labels: P1, feature

#28 Feature/27 board detail page/taiho
  public/images/BoardImage_Sample.svg
  src/pages/board/BoardDetailPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: P1, feature

#33 Feature/18 cart page/jinsu
  public/images/sample/food.svg
  src/components/CartItem.jsx
  src/pages/market/CartPage.jsx
Labels: feature

#34 Feature/29-boardnewpage/taiho
  public/icons/icon_register.svg
  public/icons/icon_register_hover.svg
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/user/MyPage.jsx
Labels: P1, feature

#36 Feature/24 search page/eunji
  src/pages/market/SearchPage.jsx
Labels: P1, feature

#37 Feature/22 detail/saebom
  package-lock.json
  package.json
  src/components/MenuItem.jsx
  src/components/PhotoReviewItem.jsx
  src/components/Product.jsx
  src/components/ReviewBox.jsx
  src/components/ReviewItem.jsx
  src/pages/market/CategoryPage.jsx
  src/pages/market/MenuPage.jsx
  src/pages/market/ProductDetailPage.jsx
  src/pages/market/ProductReviewPage.jsx
  tailwind.config.js
Labels: P1, feature

#40 feat: 네비게이션 조건부 렌더링 (#39)
  src/components/layout/index.jsx
Labels: enhancement, refactor

#42 Feature/35-ProfileDetailPage/taiho
  public/images/profile/ProfileImage_Sample.svg
  public/images/profile/Profile_sample_1.jpg
  public/images/profile/Profile_sample_2.jpg
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: P1, feature

#44 Feature/31 carousel/jinsu
  package-lock.json
  package.json
  src/components/Carousel.jsx
  src/components/layout/Header.jsx
  src/index.css
  src/pages/index.jsx
Labels: P2, feature

#47 Feature/46 button component/taiho
  src/components/Button.jsx
  src/pages/board/BoardDetailPage.jsx
Labels: enhancement

#48 Feature/38 search results page/eunji
  public/icons/icon_dropdown.svg
  public/icons/icon_sad.svg
  src/pages/market/SearchPage.jsx
  src/pages/market/SearchResultsPage.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/SignupPage.jsx
  src/routes.jsx
Labels: P1, feature

#50 Enhancement/49 main UI/jinsu
  package-lock.json
  package.json
  public/images/menu/Seafood_full.svg
  src/components/Button.jsx
  src/components/Carousel.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  tailwind.config.js
Labels: enhancement, refactor

#52 Enhancement/51 cart UI/jinsu
  src/components/Carousel.jsx
  src/components/HeaderIcon.jsx
  src/pages/market/CartPage.jsx
Labels: enhancement, P2

#56 Feature/43 create product page/taiho
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/MyPage.jsx
Labels: P1, feature

#59 Feature/57 modal/saebom
  src/components/Modal.jsx
  src/components/PurchaseModal.jsx
  src/pages/market/ProductDetailPage.jsx
Labels: bug, P1, feature

#60 Feature/58 my page enhance/taiho
  src/pages/board/BoardNewPage.jsx
  src/pages/user/MyPage.jsx
Labels: enhancement

#64 Feature/54 payment UI/jinsu
  src/components/CartItemPayment.jsx
  src/components/layout/index.jsx
  src/pages/market/PaymentPage.jsx
  src/routes.jsx
Labels: P2, refactor, feature

#67 Feature/65 payment button/jinsu
  public/images/Star.png
  src/components/Button.jsx
  src/components/Carousel.jsx
  src/components/ProductBig.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
  src/pages/market/ProductDetailPage.jsx
Labels: bug, P1, feature

#68 Feature/61 new product use form/taiho
  src/pages/board/BoardNewPage.jsx
  src/pages/market/ProductNewPage.jsx
Labels: enhancement, P1

#75 Refactor/72 code improvement/eunji
  src/components/UserForm.jsx
  src/pages/market/SearchPage.jsx
  src/pages/market/SearchResultsPage.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/SignupPage.jsx
Labels: P1, refactor

#74 Refactor/73 profile comm refactor/taiho
  src/components/Button.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: refactor

#77 Feature/71 UI check/jinsu
  src/components/CartItem.jsx
  src/components/CartItemPayment.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
Labels: bug, enhancement, feature
