Repository FRONTENDBOOTCAMP-11th/baroFarm, pull requests merged in 2025-01, with the labels that each got.

#83 Refactor/80 UI component/taiho
  src/components/NewPost.jsx
  src/components/UserForm.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: refactor

#86 Feature/69 modify UI/saebom
  public/icons/icon_star_empty.svg
  public/icons/icon_star_full.svg
  src/components/NavItem.jsx
  src/components/NewPost.jsx
  src/components/PhotoReviewItem.jsx
  src/components/Product.jsx
  src/components/PurchaseItem.jsx
  src/components/layout/Footer.jsx
  src/pages/market/PhotoReviewPage.jsx
  src/pages/market/ProductMyReviewPage.jsx
  src/pages/market/ProductNewReviewPage.jsx
  src/pages/market/ReviewPage.jsx
  src/routes.jsx
Labels: enhancement, refactor

#87 Refactor/79 code improvement/eunji
  public/icons/icon_x_thin.svg
  src/components/RecentKeywordItem.jsx
  src/components/UserForm.jsx
  src/pages/market/SearchPage.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/SignupPage.jsx
Labels: P1, refactor

#89 refactor: 검색 결과 페이지 select 구조 개선
  src/pages/market/SearchResultsPage.jsx
Labels: P1, refactor

#90 Feature/78 UI refactor/jinsu
  src/components/Button.jsx
  src/components/CartItem.jsx
  src/components/Checkbox.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
  src/pages/market/SearchBestPage.jsx
  src/pages/market/SearchNewPage.jsx
  src/pages/market/SearchSeasonalPage.jsx
Labels: bug, enhancement, P1, feature

#94 feat: useAxiosInstance 훅 만들기
  src/hooks/useAxiosInstance.js
  src/main.jsx
Labels: feature

#97 Feature/92 fetch new product/jinsu
  src/pages/index.jsx
Labels: P1, feature

#100 enhancement: 커스텀 버튼 사이즈 선택 기능 추가
  src/components/Button.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
Labels: enhancement, P1

#101 feat: 더미 데이터 수정 (#96)
  api/dbinit-sample/BaroFarmSample/data.js
Labels: documentation

#104 Feature/103 cart fetch data/jinsu
  src/components/CartItem.jsx
  src/pages/market/CartPage.jsx
Labels: bug, P1, feature

#108 Enhancement/107 add profile img/taiho
  api/dbinit-sample/BaroFarmSample/data.js
  public/icons/icon_camera.svg
  src/pages/board/BoardPageDetail.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: enhancement

#110 Feature/106 cart delete/jinsu
  .gitignore
  src/components/CartItem.jsx
  src/components/HeaderIcon.jsx
  src/pages/market/CartPage.jsx
Labels: P1, feature

#112 Feature/102 product/saebom
  src/components/MenuItem.jsx
  src/components/Product.jsx
  src/components/Products.jsx
  src/pages/market/CategoryPage.jsx
  src/pages/market/MenuPage.jsx
Labels: P1, feature

#114 Feature/111 init data user store/jinsu
  api/dbinit-sample/BaroFarmSample/data.js
  src/components/HeaderIcon.jsx
  src/pages/index.jsx
  src/zustand/readme.md
  src/zustand/useUserStore.js
Labels: bug, P1, feature

#118 Feature/99 signup/eunji
  src/components/UserForm.jsx
  src/pages/user/ProfilePage.jsx
  src/pages/user/SignupPage.jsx
Labels: P1, feature

#121 Feature/109 board detail page/taiho
  api/bruno-sample/baroFarmApi/05.게시판(QnA, 공지 등)/01.목록 조회/게시물 목록 조회.bru
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/Comment.jsx
  src/pages/board/CommentItem.jsx
  src/pages/market/ProductNewPage.jsx
Labels: P1, feature

#123 feat: 더미데이터 수정 (리뷰데이터 추가)
  api/dbinit-sample/BaroFarmSample/data.js
Labels: documentation

#124 Feature/122 new post/taiho
  api/bruno-sample/baroFarmApi/01.회원/01 회원가입,로그인/일반 회원 로그인(_id=4).bru
  api/bruno-sample/baroFarmApi/06.시스템/01.파일/파일 업로드.bru
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: P1, feature

#128 Feature/115 payment/jinsu
  api/dbinit-sample/BaroFarmSample/data.js
  src/components/CartItem.jsx
  src/components/CartItemPayment.jsx
  src/components/ProductToBuy.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
Labels: bug, P1, feature

#131 Feature/119 login/eunji
  src/components/UserForm.jsx
  src/hooks/useAxiosInstance.js
  src/pages/user/LoginPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/SignupPage.jsx
Labels: enhancement, P1, feature

#133 Fix/130 cart payment/jinsu
  src/components/CartItem.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
Labels: bug, P1

#134 Fix/129 main page/jinsu
  src/components/Carousel.jsx
  src/components/ProductBig.jsx
  src/pages/index.jsx
  src/pages/market/SearchBestPage.jsx
  src/pages/market/SearchNewPage.jsx
  src/pages/market/SearchSeasonalPage.jsx
Labels: bug, P1

#136 Feature/125 new product/taiho
  .gitignore
  api/dbinit-sample/BaroFarmSample/data.js
  public/images/Sample_apple.jpg
  public/images/Sample_kimchiCake.png
  src/pages/board/BoardNewPage.jsx
  src/pages/market/ProductNewPage.jsx
Labels: enhancement, P1, feature

#138 Refactor/135 axios instance/jinsu
  package-lock.json
  package.json
  public/images/PG-logos/kakaopay.jpg
  public/images/PG-logos/payco.png
  public/images/PG-logos/tosspay.jpg
  src/components/HeaderIcon.jsx
  src/components/PGButton.jsx
  src/components/PaymentModal.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
Labels: P1, P3, refactor, feature

#141 Feature/132 search/eunji
  src/pages/market/SearchPage.jsx
  src/pages/market/SearchResultsPage.jsx
Labels: P2, feature

#143 Feature/139 my page login/taiho
  src/components/HeaderIcon.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: P1, feature

#145 [feature] 결제 페이지 배송지 관리 기능 추가
  api/bruno-sample/baroFarmApi/01.회원/02.회원 정보 수정/회원 정보 수정(중첩 속성, extra.address).bru
  api/bruno-sample/baroFarmApi/01.회원/04.회원 정보 조회/지정한 회원 정보 조회(모든 속성).bru
  api/bruno-sample/baroFarmApi/02.일반 회원/04.장바구니/장바구니에 상품 추가.bru
  src/components/AddressModal.jsx
  src/components/Button.jsx
  src/components/Product.jsx
  src/pages/market/PaymentPage.jsx
  src/routes.jsx
Labels: enhancement, P2, feature

#147 Feature/142 recent search management/eunji
  public/icons/icon_x_green.svg
  public/icons/icon_x_white.svg
  src/components/RecentKeywordItem.jsx
  src/pages/market/SearchPage.jsx
Labels: P2, feature

#152 Feature/146 payment complete/jinsu
  public/icons/icon_check.svg
  src/hooks/readme.md
  src/pages/market/CartPage.jsx
  src/pages/market/OrderCompletePage.jsx
  src/pages/market/PaymentPage.jsx
  src/routes.jsx
Labels: enhancement, P2, feature

#153 Feature/150 autologin/eunji
  package-lock.json
  package.json
  public/icons/icon_check_white.svg
  src/pages/user/LoginPage.jsx
Labels: P2, feature

#154 Feature/127 like/saebom
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-carrot.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-chicken.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-duck.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-fruitset.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-grape.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-kimchi.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-pizza.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-pork.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-potato.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-review1.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-review2.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-review3.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-review4.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-review5.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-rice.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-ricecake.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-seaweed.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-seaweed2.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-shine.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-shrimp.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-strawberry.png
  api/dbinit-sample/BaroFarmSample/uploadFiles/sample-sweetpotato.png
  src/components/Product.jsx
  src/hooks/useCategory.js
  src/hooks/useLikeToggle.js
  src/pages/market/CategoryPage.jsx
  src/pages/market/ProductDetailPage.jsx
  src/pages/user/BookmarkPage.jsx
Labels: P1, feature

#160 Feature/159 comment/taiho
  src/components/assets/react.svg
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/Comment.jsx
  src/pages/board/CommentItem.jsx
  src/pages/board/createdTime.js
Labels: P2, feature

#162 Feature/161 comment delete/taiho
  src/components/createdTime.js
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardEditPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/Comment.jsx
  src/pages/board/CommentItem.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/ProfilePage.jsx
Labels: feature

#166 Feature/156 juso api/jinsu
  public/images/BaroFarmLogo.png
  public/images/BaroFarmLogo_long.png
  src/components/AddressModal.jsx
  src/components/PostcodeSearch.jsx
  src/components/layout/Header.jsx
  src/pages/index.jsx
  src/pages/market/OrderCompletePage.jsx
  src/pages/market/PaymentPage.jsx
Labels: enhancement, P3, feature

#168 Feature/163 my product/taiho
  public/images/Sample_Sushi.png
  src/components/NewPost.jsx
  src/components/SoldItem.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/Comment.jsx
  src/pages/board/CommentItem.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/SalePage.jsx
Labels: bug, P3, feature

#171 Feature/169 main page/jinsu
  api/bruno-sample/baroFarmApi/01.회원/01 회원가입,로그인/일반 회원 로그인(_id=4).bru
  src/components/Carousel.jsx
  src/components/PaymentModal.jsx
  src/components/ProductToBuy.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/OrderCompletePage.jsx
  src/pages/market/PaymentPage.jsx
  src/pages/market/ProductDetailPage.jsx
Labels: bug, P2, feature

#173 Feature/170 board search/taiho
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardPage.jsx
Labels: P3, feature

#174 Feature/165 connect/saebom
  src/components/Modal.jsx
  src/hooks/useAxiosInstance.js
  src/hooks/useCategory.js
  src/hooks/useLikeToggle.js
  src/pages/market/ProductDetailPage.jsx
  src/pages/market/ProductNewReviewPage.jsx
  src/pages/market/ReviewPage.jsx
  src/pages/user/PurchasePage.jsx
Labels: P3, feature

#178 Feature/172 fetch bookmark/jinsu
  api/dbinit-sample/BaroFarmSample/data.js
  src/components/Carousel.jsx
  src/components/CartItem.jsx
  src/components/ProductBig.jsx
  src/components/ProductSmall.jsx
  src/hooks/useLikeToggle.js
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
Labels: P2, feature

#181 Feature/175 sale edit/taiho
  src/components/ProductInfoForm.jsx
  src/components/SoldItem.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/CommentItem.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/EditProduct.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/SalePage.jsx
  src/routes.jsx
  src/utils/createdTime.js
Labels: P3, feature

#184 fix: 에러 수정
  src/pages/user/BookmarkPage.jsx
  src/pages/user/RecentPage.jsx
Labels: bug

#185 feature/myPost/taiho
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/CommentItem.jsx
  src/pages/user/MyPostPage.jsx
  src/pages/user/ProfilePage.jsx
  src/pages/user/SalePage.jsx
  vite.config.js
Labels: P3, feature

#190 Feature/179 cart select all/jinsu
  src/components/CartItem.jsx
  src/components/Checkbox.jsx
  src/hooks/useAxiosInstance.js
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
Labels: P3, feature

#193 Feature/157 social auth/eunji
  index.html
  public/images/login/kakaoLogo.png
  src/components/UserForm.jsx
  src/hooks/useAxiosInstance.js
  src/pages/market/SearchResultsPage.jsx
  src/pages/user/KakaoAuthPage.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/SignupPage.jsx
  src/routes.jsx
Labels: P3, feature

#194 Enhancement/189 profile enhance/taiho
  src/components/UserForm.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/user/EditProduct.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/MyPostPage.jsx
  src/pages/user/ProfilePage.jsx
  src/pages/user/SalePage.jsx
Labels: refactor

#196 Enhancement/payment address/jinsu
  api/bruno-sample/baroFarmApi/01.회원/01 회원가입,로그인/일반 회원 로그인(_id=4).bru
  api/bruno-sample/baroFarmApi/01.회원/02.회원 정보 수정/회원 정보 수정(여러 속성, phone, name).bru
  src/components/AddressModal.jsx
  src/pages/market/PaymentPage.jsx
Labels: bug, P1

#198 프로필 수정 페이지 변경 및 우편주소 API 적용
  src/components/UserForm.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/ProfilePage.jsx
Labels: refactor

#204 Refactor/203 QA1/eunji
  src/components/UserForm.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/SignupPage.jsx
Labels: bug, enhancement, P1

#205 Feature/202 qa 1/saebom
  src/components/NewPost.jsx
  src/components/PhotoReviewItem.jsx
  src/components/Product.jsx
  src/components/PurchaseItem.jsx
  src/pages/market/CategoryPage.jsx
  src/pages/market/MenuPage.jsx
  src/pages/market/ProductDetailPage.jsx
  src/pages/market/ReviewPage.jsx
  src/pages/user/BookmarkPage.jsx
  src/pages/user/MyPostPage.jsx
  src/pages/user/PurchasePage.jsx
  src/pages/user/RecentPage.jsx
Labels: enhancement

#206 fix: 에러페이지 수정
  src/components/Product.jsx
  src/components/Products.jsx
  src/pages/ErrorPage.jsx
Labels: enhancement

#207 Refactor/200 qa2/taiho
  netlify.toml
  public/images/profile/ProfileImage_Sample.jpg
  public/images/profile/ProfileImage_Sample.svg
  src/components/NewPost.jsx
  src/components/UserForm.jsx
  src/hooks/useAxiosInstance.js
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardEditPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/Comment.jsx
  src/pages/board/CommentItem.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: refactor

#211 Fix/201 qa/jisnu
  index.html
  src/components/AddressModal.jsx
  src/components/Carousel.jsx
  src/components/HeaderIcon.jsx
  src/components/PaymentModal.jsx
  src/components/PostcodeSearch.jsx
  src/components/ProductSmall.jsx
  src/components/layout/Footer.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
  src/pages/market/SearchBestPage.jsx
  src/pages/market/SearchNewPage.jsx
  src/pages/market/SearchSeasonalPage.jsx
  src/utils/getMonthlyData.js
Labels: bug, enhancement, P1

#210 fix: 오타수정
  src/components/UserForm.jsx
  src/pages/board/BoardPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: bug, enhancement

#213 Fix/212 qa2/taiho
  api/dbinit-sample/BaroFarmSample/data.js
  src/components/NewPost.jsx
  src/components/Pagination.jsx
  src/components/ProductInfoForm.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/board/BoardPageDetail.jsx
  src/pages/board/CommentItem.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/ProfilePage.jsx
Labels: bug, refactor

#215 Fix/214 moblie easypay/jinsu
  src/components/AddressModal.jsx
  src/components/PaymentModal.jsx
  src/pages/market/PaymentPage.jsx
Labels: bug, P1

#217 feat: 로그인 안하고 구매 버튼 클릭
  src/pages/market/ProductDetailPage.jsx
Labels: bug

#218 Fix/202 qa2/taiho
  api/dbinit-sample/BaroFarmSample/data.js
  src/components/UserForm.jsx
Labels: bug, enhancement, refactor

#222 fix: 모바일에서 결제 완료 페이지 안 뜨는 문제 해결
  src/pages/market/OrderCompletePage.jsx
  src/pages/market/PaymentPage.jsx
Labels: bug, P1

#238 feat: 회원가입, 로그인, 검색, 검색결과 페이지 타이틀 추가
  src/pages/market/SearchPage.jsx
  src/pages/market/SearchResultsPage.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/SignupPage.jsx
Labels: feature

#239 feature/게시판, 마이 페이지, 장바구니 및 주문 페이지 타이틀 추가
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardEditPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/BoardPage.jsx
  src/pages/index.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/OrderCompletePage.jsx
  src/pages/market/PaymentPage.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/user/EditProduct.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/MyPostPage.jsx
  src/pages/user/ProfilePage.jsx
  src/pages/user/SalePage.jsx
Labels: P3, feature

#240 feat: Helmet 추가
  src/pages/DataErrorPage.jsx
  src/pages/ErrorPage.jsx
  src/pages/market/CategoryPage.jsx
  src/pages/market/MenuPage.jsx
  src/pages/market/ProductDetailPage.jsx
  src/pages/market/ProductNewReviewPage.jsx
  src/pages/market/ReviewPage.jsx
  src/pages/user/BookmarkPage.jsx
  src/pages/user/PurchasePage.jsx
  src/pages/user/RecentPage.jsx
Labels: enhancement

#244 Enhancement/243 to toast/taiho
  src/App.jsx
  src/components/AddressModal.jsx
  src/components/PaymentModal.jsx
  src/components/ProductSmall.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/board/BoardEditPage.jsx
  src/pages/board/BoardNewPage.jsx
  src/pages/board/Comment.jsx
  src/pages/board/CommentItem.jsx
  src/pages/market/CartPage.jsx
  src/pages/market/PaymentPage.jsx
  src/pages/market/ProductNewPage.jsx
  src/pages/market/ProductNewReviewPage.jsx
  src/pages/market/SearchPage.jsx
  src/pages/user/EditProduct.jsx
  src/pages/user/EditProfilePage.jsx
  src/pages/user/KakaoAuthPage.jsx
  src/pages/user/LoginPage.jsx
  src/pages/user/ProfilePage.jsx
  src/pages/user/SignupPage.jsx
Labels: enhancement

#250 feat: 간단하게 README 작성
  README.md
  public/images/reademe/eunji.png
  public/images/reademe/jinsu.png
  public/images/reademe/seabom.png
  public/images/reademe/taiho.png
Labels: documentation

#251 feat: README파일 텍스트 가운데 정렬
  README.md
Labels: documentation
